version: '3'
services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www/html/excel
        networks:
            - app-network
        container_name: php-1
    nginx:
        container_name: nginx-excel
        image: nginx:latest
        ports:
            - 8085:80
        volumes:
            - ./nginx:/etc/nginx/conf.d
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
